### ISSUE TITLE
treep doesn't work

### ISSUE THREAD

**Issue by ddliu365** [machines-in-motion/dg_tutorial_with_turtlesim#2]
After installing ubuntu scripts, `treep` command seems not work.

I didn't get all the codes needed to run this tutorial which have a lot of dependencies.

Can you provide a more detailed way to compile this tutorial?

**Comment by luneart** [comment]
Actually treep works very well - it's the "DG_TUTORIAL" project that doesn't exists (anymore?) in the repo.
If you checked the treep doc you read that you can do a `treep --projects` to check out the available projects. And as we're doing a tuto on the dynamic graph manager... well, a `treep --clone DYNAMIC_GRAPH_MANAGER`does work pretty well.

**Comment by ddliu365** [comment]
Yes, I will try. Thanks.
